Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -35,6 +35,9 @@ jobs:
           apt-get update
           apt-get install -y gcc-arm-none-eabi
           echo "GNUARMEMB_TOOLCHAIN_PATH=/usr" >> $GITHUB_ENV
+      - name: Print ZMK App Kconfig
+        run: |
+          cat zmk/app/Kconfig || echo "ZMK app Kconfig file not found"
       - name: West Build (le_jlwffre)
         run: |
           west build -s zmk/app -b le_jlwffre -- -DZMK_CONFIG="${GITHUB_WORKSPACE}/config" -DSHIELD=le_jlwffre -DZMK_EXTRA_MODULES="${GITHUB_WORKSPACE}" -DCMAKE_VERBOSE_MAKEFILE=ON
